package com.dtcc.recon.web.dto;


import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class ClientPropertiesDto {

    //User_id is not available as it is autogenerated
    private long userId;

    private String userName;

    private String password;

    private String brokerFirm;

    private String image;
}
